# Generated by Django 4.1.3 on 2022-11-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesAPI', '0003_alter_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='original_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
