# Generated by Django 4.1.3 on 2022-11-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesAPI', '0005_alter_image_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original_url',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
