# Generated by Django 4.1.3 on 2022-11-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesAPI', '0008_image_thumbnail_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail_urls',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
