# Generated by Django 4.1.3 on 2022-11-24 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesAPI', '0010_alter_thumbnail_th_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='th_height',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
